# -*- coding: utf-8 -*-
"""DL_exp6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_mPKU9upiSHen3HrwfiFUf4zFzCf_3a
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense, Dropout
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import pickle

# Movie & Book Quotes Dataset
corpus = [
    "to be or not to be that is the question",
    "all that glitters is not gold",
    "the only way to do great work is to love what you do",
    "in the middle of every difficulty lies opportunity",
    "it does not matter how slowly you go as long as you do not stop",
    "life is what happens when you are busy making other plans",
    "the future belongs to those who believe in the beauty of their dreams",
    "it is during our darkest moments that we must focus to see the light",
    "the best time to plant a tree was twenty years ago the second best time is now",
    "an unexamined life is not worth living",
    "spread love everywhere you go let no one ever come to you without leaving happier",
    "when you reach the end of your rope tie a knot in it and hang on",
    "always remember that you are absolutely unique just like everyone else",
    "do not go where the path may lead go instead where there is no path and leave a trail",
    "you will face many defeats in life but never let yourself be defeated",
    "the greatest glory in living lies not in never falling but in rising every time we fall",
    "in the end it is not the years in your life that count it is the life in your years",
    "never let the fear of striking out keep you from playing the game",
    "life is either a daring adventure or nothing at all",
    "many of life greatest fears are situations that will never come to pass",
    "you have brains in your head you have feet in your shoes",
    "if life were predictable it would cease to be life and be without flavor",
    "if you look at what you have in life you will always have more",
    "if you set your goals ridiculously high and it is a failure you will fail above everyone else success",
    "if life is a journey then let every step be a learning experience",
    "the mind is everything what you think you become",
    "the best revenge is massive success",
    "in three words i can sum up everything i have learned about life it goes on",
    "if you want to live a happy life tie it to a goal not to people or things",
    "never let the fear of striking out keep you from playing the game of life",
    "money and success do not change people they merely amplify what is already there",
    "your time is limited so do not waste it living someone else life",
    "if you want to make a permanent change stop focusing on the size of your problems",
    "you become what you believe and not what you think you are",
    "the two most important days in your life are the day you are born and the day you find out why",
    "the most common way people give up their power is by thinking they do not have any",
    "the mind is not a vessel to be filled but a fire to be ignited",
    "you only live once but if you do it right once is enough",
    "be yourself everyone else is already taken",
    "two roads diverged in a wood and i took the one less traveled by",
]

print(f"Total quotes: {len(corpus)}")
print("Sample:", corpus[0])

# Tokenize
tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)
total_words = len(tokenizer.word_index) + 1
print(f"Vocabulary size: {total_words}")

# Create n-gram sequences
input_sequences = []
for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        input_sequences.append(token_list[:i+1])

print(f"Total sequences: {len(input_sequences)}")

# Pad sequences
max_seq_len = max(len(x) for x in input_sequences)
input_sequences = np.array(pad_sequences(input_sequences,
                                          maxlen=max_seq_len,
                                          padding='pre'))

# Split X and y
X = input_sequences[:, :-1]
y = input_sequences[:, -1]
y_cat = to_categorical(y, num_classes=total_words)

# Train/val split
X_train, X_val, y_train, y_val = train_test_split(X, y_cat,
                                                    test_size=0.2,
                                                    random_state=42)
print(f"X_train: {X_train.shape}, X_val: {X_val.shape}")

model = Sequential([
    Embedding(total_words, 64, input_length=max_seq_len - 1),
    Bidirectional(LSTM(128, return_sequences=True)),
    Dropout(0.3),
    Bidirectional(LSTM(64)),
    Dropout(0.3),
    Dense(total_words, activation='softmax')
])

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
model.summary()

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=200,
    verbose=1
)

print("Training complete!")

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].plot(history.history['accuracy'], label='Train Accuracy')
axes[0].plot(history.history['val_accuracy'], label='Val Accuracy')
axes[0].set_title('Model Accuracy')
axes[0].set_xlabel('Epoch')
axes[0].legend()

axes[1].plot(history.history['loss'], label='Train Loss')
axes[1].plot(history.history['val_loss'], label='Val Loss')
axes[1].set_title('Model Loss')
axes[1].set_xlabel('Epoch')
axes[1].legend()

plt.tight_layout()
plt.savefig("training_plot.png")
plt.show()

def predict_next_word(text, model, tokenizer, max_seq_len):
    token_list = tokenizer.texts_to_sequences([text.lower()])[0]
    token_list = pad_sequences([token_list],
                                maxlen=max_seq_len - 1,
                                padding='pre')
    predicted = model.predict(token_list, verbose=0)
    predicted_index = np.argmax(predicted)
    for word, index in tokenizer.word_index.items():
        if index == predicted_index:
            return word
    return ""

# Test predictions
test_sentences = [
    "to be or not",
    "the best time to",
    "life is what",
    "the mind is",
    "you only live",
]

print("── Next Word Predictions ──")
for sentence in test_sentences:
    next_word = predict_next_word(sentence, model, tokenizer, max_seq_len)
    print(f"  '{sentence}' → '{next_word}'")

# Save model and tokenizer
model.save("movie_quotes_bilstm.h5")
with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)
print("\nModel and tokenizer saved!")