# -*- coding: utf-8 -*-
"""DLexp_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yvnhhbqu5E99no5F8LTQcojnzcnPqy10
"""

!pip install optuna -q

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import optuna
import matplotlib.pyplot as plt

# 1. Generate Synthetic Student Dataset
np.random.seed(42)
n_samples = 2000

data = pd.DataFrame({
    "sleep_hours":           np.random.uniform(4, 10, n_samples),
    "previous_gpa":          np.random.uniform(2.0, 4.0, n_samples),
    "extracurricular":       np.random.randint(0, 2, n_samples),
    "attendance_percentage": np.random.uniform(50, 100, n_samples)
})

data["overall_performance"] = (
    data["sleep_hours"]           * 2.5  +
    data["previous_gpa"]          * 15.0 +
    data["extracurricular"]       * 5.0  +
    data["attendance_percentage"] * 0.4  +
    np.random.normal(0, 3, n_samples)
).clip(0, 100)

# 2. Preprocess
features = ["sleep_hours", "previous_gpa", "extracurricular", "attendance_percentage"]
X = data[features]
y = data[["overall_performance"]]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# 3. Optuna Model Builder
def create_model(trial):
    n_layers = trial.suggest_int("n_layers", 1, 3)
    n_units  = trial.suggest_int("n_units", 32, 128)
    lr       = trial.suggest_float("learning_rate", 1e-4, 1e-2, log=True)
    model = tf.keras.Sequential()
    model.add(layers.Dense(n_units, activation="relu", input_shape=(X_train.shape[1],)))
    for _ in range(n_layers):
        model.add(layers.Dense(n_units, activation="relu"))
    model.add(layers.Dense(1))
    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=lr), loss="mse", metrics=["mae"])
    return model

def objective(trial):
    model = create_model(trial)
    batch_size = trial.suggest_categorical("batch_size", [16, 32, 64])
    history = model.fit(X_train, y_train, validation_split=0.2,
                        epochs=20, batch_size=batch_size, verbose=0)
    return min(history.history["val_loss"])

# 4. Run Optuna
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=20)
print("Best Params:", study.best_params)

# 5. Train Final Model
params = study.best_params
final_model = tf.keras.Sequential()
final_model.add(layers.Dense(params["n_units"], activation="relu", input_shape=(X_train.shape[1],)))
for _ in range(params["n_layers"]):
    final_model.add(layers.Dense(params["n_units"], activation="relu"))
final_model.add(layers.Dense(1))
final_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=params["learning_rate"]),
                    loss="mse", metrics=["mae"])

history = final_model.fit(X_train, y_train, epochs=50,
                          batch_size=params["batch_size"],
                          validation_split=0.2, verbose=1)

# 6. Evaluate
loss, mae = final_model.evaluate(X_test, y_test, verbose=0)
print(f"\nTest MSE Loss : {loss:.4f}")
print(f"Test MAE      : {mae:.4f}")

# 7. Predict Sample Student
new_student = np.array([[7.0, 3.2, 1, 85.0]])
new_student_scaled = scaler.transform(new_student)
prediction = final_model.predict(new_student_scaled)
print(f"\nPredicted Overall Performance: {prediction[0][0]:.2f} / 100")

# 8. Plot
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].plot(history.history["loss"], label="Train Loss")
axes[0].plot(history.history["val_loss"], label="Val Loss")
axes[0].set_title("MSE Loss"); axes[0].legend()
axes[1].plot(history.history["mae"], label="Train MAE")
axes[1].plot(history.history["val_mae"], label="Val MAE")
axes[1].set_title("MAE"); axes[1].legend()
plt.tight_layout()
plt.savefig("training_plot.png")
plt.show()